---
- name: Copy SAR files to NFS location
  hosts: localhost
  gather_facts: false

  vars:
    nfs_mount_point: arjun/mount/path
    sar_files_path: arjun/var/log/sa/

  tasks:
    - name: Create destination directory on NFS
      file:
        path: "{{ nfs_mount_point }}"
        state: directory

    - name: Find SAR files
      find:
        paths: "{{ sar_files_path }}"
        patterns: "sar*"
        recurse: no
      register: sar_files

    - name: Gather hostname
      command: hostname
      register: hostname_output


    - name: debug
      debug:
        var: sar_files

    - name: Copy SAR files to NFS location
      copy:
        src: "{{ item.path }}"
        dest: "{{ nfs_mount_point }}/{{ item.path | basename }}_hostname_output"
      loop: "{{ sar_files.files }}"
