---
- name: Copy sar output file
  hosts: all_OSP
  gather_facts: true
  become: true
  become_user: heat-stack
  vars:
    nfs_mount_point: /root/testpath
  tasks:
    - name: Create destination directory on NFS
      file:
        path: "{{ nfs_mount_point }}"
        state: directory

    - name: Collect file names
      shell: 'ls /var/log/sa/sa?? | xargs -i sar -A -f {} > /tmp/sar_$(uname -n).txt'

    - name: Get hostname
      shell: uname -n
      register: hostname_details

    - name: Copy file to specific location
      copy:
        src: "/tmp/sar_{{ hostname_details.stdout }}.txt"
        dest: "{{ nfs_mount_point }}"
        remote_src: yes 
